export { CtaBanner } from './CtaBanner'
export { Faq } from './Faq'
export { Features } from './Features'
export { Hero } from './Hero'
export { HowItWorks } from './HowItWorks'
export { MarketingFooter } from './MarketingFooter'
export { MarketingNav } from './MarketingNav'
export { Pricing } from './Pricing'
export { Replaces } from './Replaces'
export { Section, SectionHeading } from './Section'
export { Spotlight } from './Spotlight'
export { Testimonials } from './Testimonials'
